# -*- coding: utf-8 -*-
"""Major Project(SmartKnower).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1db3Qj-bOxJjuu06pu6OKYOK7Eh6dy8IK

#Smartknow(Major Project)
"""

import pandas as pd
df = pd.read_csv('/content/owid-covid-data (1).csv')
df

df.isnull().sum()

df.rename(columns = {'total_cases' : 'y','date':'ds'},inplace = True)

df=df.iloc[30325:30728,:]
df

df_new = df[['ds','y']]
df_new

df_new.info()

df_new['ds'] = pd.to_datetime(df_new['ds'])

df_new.info()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(15,5))
plt.plot(df_new['ds'],df_new['y'])
plt.xlabel('Date')
plt.ylabel('Cases')
plt.show()

import fbprophet

op = fbprophet.Prophet(changepoint_prior_scale=0.5)
op.fit(df_new)

forecast = op.make_future_dataframe(periods = 30 ,freq = 'D')
forecast = op.predict(forecast)

forecast.columns

forecast[['ds','yhat','yhat_lower','yhat_upper']]

op.plot(forecast,xlabel = 'Date',ylabel='Cases');